import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <div className="fixed top-0 left-0 w-full h-screen bg-[url('/images/background.jpg')] bg-cover">
          <div className="w-full h-full bg-black bg-opacity-50 backdrop-blur-lg"></div>
        </div>
        <Sidebar />
        <div className="absolute z-10 top-0 left-0 min-h-screen w-full">
          {children}
        </div>
      </body>
    </html>
  );
}
