name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/citations/requirements.txt

      - name: Generate citations
        run: python scripts/citations/cite.py
        env:
          MANUBOT_USE_DOCKER: false

      # Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # Changed from npm ci to npm install
      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
